# Generated by Django 5.2.1 on 2025-09-03 07:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="actual_cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="实际成本",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="budget",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="项目预算",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="end_date",
            field=models.DateField(blank=True, null=True, verbose_name="项目结束日期"),
        ),
        migrations.AddField(
            model_name="project",
            name="priority",
            field=models.CharField(
                choices=[
                    ("low", "低"),
                    ("medium", "中"),
                    ("high", "高"),
                    ("urgent", "紧急"),
                ],
                default="medium",
                max_length=10,
                verbose_name="项目优先级",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="progress",
            field=models.IntegerField(default=0, verbose_name="项目进度百分比"),
        ),
        migrations.AddField(
            model_name="project",
            name="start_date",
            field=models.DateField(blank=True, null=True, verbose_name="项目开始日期"),
        ),
        migrations.AddField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("planning", "规划中"),
                    ("active", "进行中"),
                    ("on_hold", "暂停"),
                    ("completed", "已完成"),
                    ("cancelled", "已取消"),
                ],
                default="planning",
                max_length=20,
                verbose_name="项目状态",
            ),
        ),
        migrations.CreateModel(
            name="Milestone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="里程碑名称")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="里程碑描述"),
                ),
                ("due_date", models.DateField(verbose_name="截止日期")),
                (
                    "completed",
                    models.BooleanField(default=False, verbose_name="是否完成"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="完成时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="milestones",
                        to="projects.project",
                        verbose_name="项目",
                    ),
                ),
            ],
            options={
                "verbose_name": "里程碑",
                "verbose_name_plural": "里程碑",
                "ordering": ["due_date"],
            },
        ),
        migrations.CreateModel(
            name="ProjectTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="模板名称")),
                ("description", models.TextField(blank=True, verbose_name="模板描述")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("software", "软件开发"),
                            ("marketing", "市场营销"),
                            ("research", "研究项目"),
                            ("construction", "建设工程"),
                            ("event", "活动策划"),
                            ("other", "其他"),
                        ],
                        default="other",
                        max_length=50,
                        verbose_name="模板类别",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(default=False, verbose_name="是否公开"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
            ],
            options={
                "verbose_name": "项目模板",
                "verbose_name_plural": "项目模板",
                "ordering": ["-created_at"],
            },
        ),
    ]
