# Generated by Django 5.2.1 on 2025-09-03 07:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "projects",
            "0002_project_actual_cost_project_budget_project_end_date_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalyticsCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cache_key",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="缓存键"
                    ),
                ),
                ("cache_data", models.JSONField(verbose_name="缓存数据")),
                ("expires_at", models.DateTimeField(verbose_name="过期时间")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "分析缓存",
                "verbose_name_plural": "分析缓存",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["cache_key", "expires_at"],
                        name="analytics_a_cache_k_0d5319_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DashboardWidget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="组件名称")),
                (
                    "widget_type",
                    models.CharField(
                        choices=[
                            ("chart", "图表"),
                            ("metric", "指标"),
                            ("table", "表格"),
                            ("list", "列表"),
                            ("progress", "进度条"),
                        ],
                        max_length=20,
                        verbose_name="组件类型",
                    ),
                ),
                ("config", models.JSONField(verbose_name="组件配置")),
                ("position", models.IntegerField(default=0, verbose_name="位置排序")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dashboard_widgets",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "仪表板组件",
                "verbose_name_plural": "仪表板组件",
                "ordering": ["user", "position"],
            },
        ),
        migrations.CreateModel(
            name="DataExport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "export_type",
                    models.CharField(
                        choices=[
                            ("project_summary", "项目汇总"),
                            ("task_details", "任务详情"),
                            ("team_performance", "团队绩效"),
                            ("time_tracking", "工时统计"),
                            ("custom_report", "自定义报告"),
                        ],
                        max_length=30,
                        verbose_name="导出类型",
                    ),
                ),
                (
                    "export_format",
                    models.CharField(
                        choices=[
                            ("excel", "Excel"),
                            ("csv", "CSV"),
                            ("pdf", "PDF"),
                            ("json", "JSON"),
                        ],
                        max_length=10,
                        verbose_name="导出格式",
                    ),
                ),
                (
                    "file_path",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="文件路径"
                    ),
                ),
                (
                    "file_size",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="文件大小(字节)"
                    ),
                ),
                (
                    "filters",
                    models.JSONField(default=dict, verbose_name="导出筛选条件"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "等待中"),
                            ("processing", "处理中"),
                            ("completed", "已完成"),
                            ("failed", "失败"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="导出状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="完成时间"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="错误信息"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_exports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "数据导出",
                "verbose_name_plural": "数据导出",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjectReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("progress", "进度报告"),
                            ("performance", "绩效报告"),
                            ("resource", "资源报告"),
                            ("timeline", "时间线报告"),
                            ("cost", "成本报告"),
                            ("quality", "质量报告"),
                        ],
                        max_length=20,
                        verbose_name="报告类型",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="报告标题")),
                ("content", models.JSONField(verbose_name="报告内容")),
                (
                    "generated_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="生成时间"),
                ),
                ("period_start", models.DateField(verbose_name="统计开始日期")),
                ("period_end", models.DateField(verbose_name="统计结束日期")),
                (
                    "generated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="生成者",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="projects.project",
                        verbose_name="项目",
                    ),
                ),
            ],
            options={
                "verbose_name": "项目报告",
                "verbose_name_plural": "项目报告",
                "ordering": ["-generated_at"],
            },
        ),
        migrations.CreateModel(
            name="TeamPerformance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_tasks",
                    models.IntegerField(default=0, verbose_name="总任务数"),
                ),
                (
                    "completed_tasks",
                    models.IntegerField(default=0, verbose_name="完成任务数"),
                ),
                (
                    "overdue_tasks",
                    models.IntegerField(default=0, verbose_name="逾期任务数"),
                ),
                (
                    "estimated_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=8,
                        verbose_name="预估工时",
                    ),
                ),
                (
                    "actual_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=8,
                        verbose_name="实际工时",
                    ),
                ),
                (
                    "task_completion_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="任务完成率(%)",
                    ),
                ),
                (
                    "on_time_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="按时完成率(%)",
                    ),
                ),
                ("period_start", models.DateField(verbose_name="统计开始日期")),
                ("period_end", models.DateField(verbose_name="统计结束日期")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_performance",
                        to="projects.project",
                        verbose_name="项目",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performance_records",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "团队绩效",
                "verbose_name_plural": "团队绩效",
                "ordering": ["-period_end", "-task_completion_rate"],
                "unique_together": {("user", "project", "period_start", "period_end")},
            },
        ),
    ]
