# Generated by Django 5.2.1 on 2025-09-03 07:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "projects",
            "0002_project_actual_cost_project_budget_project_end_date_and_more",
        ),
        ("tasks", "0002_tasktag_task_actual_hours_task_completed_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkflowInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="实例名称")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "运行中"),
                            ("completed", "已完成"),
                            ("cancelled", "已取消"),
                            ("error", "错误"),
                        ],
                        default="running",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="开始时间"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="完成时间"
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("approved", "已批准"),
                            ("rejected", "已拒绝"),
                            ("cancelled", "已取消"),
                            ("error", "错误"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="工作流结果",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="备注")),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workflows",
                        to="projects.project",
                        verbose_name="关联项目",
                    ),
                ),
                (
                    "started_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="发起者",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workflows",
                        to="tasks.task",
                        verbose_name="关联任务",
                    ),
                ),
            ],
            options={
                "verbose_name": "工作流实例",
                "verbose_name_plural": "工作流实例",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="ApprovalRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="审批标题")),
                ("description", models.TextField(verbose_name="审批描述")),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("task_creation", "任务创建"),
                            ("task_modification", "任务修改"),
                            ("project_change", "项目变更"),
                            ("budget_adjustment", "预算调整"),
                            ("resource_allocation", "资源分配"),
                            ("custom", "自定义"),
                        ],
                        max_length=50,
                        verbose_name="审批类型",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "低"),
                            ("normal", "普通"),
                            ("high", "高"),
                            ("urgent", "紧急"),
                        ],
                        default="normal",
                        max_length=10,
                        verbose_name="优先级",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("submitted", "已提交"),
                            ("under_review", "审核中"),
                            ("approved", "已批准"),
                            ("rejected", "已拒绝"),
                            ("cancelled", "已取消"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="审批状态",
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="提交时间"
                    ),
                ),
                (
                    "deadline",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="截止时间"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="完成时间"
                    ),
                ),
                (
                    "attachments",
                    models.JSONField(default=list, verbose_name="附件信息"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="备注")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_requests",
                        to="projects.project",
                        verbose_name="关联项目",
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="申请人",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_requests",
                        to="tasks.task",
                        verbose_name="关联任务",
                    ),
                ),
                (
                    "workflow_instance",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_requests",
                        to="workflows.workflowinstance",
                        verbose_name="工作流实例",
                    ),
                ),
            ],
            options={
                "verbose_name": "审批请求",
                "verbose_name_plural": "审批请求",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkflowStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="步骤名称")),
                (
                    "step_type",
                    models.CharField(
                        choices=[
                            ("approval", "审批"),
                            ("review", "审核"),
                            ("notification", "通知"),
                            ("action", "操作"),
                            ("condition", "条件判断"),
                        ],
                        max_length=20,
                        verbose_name="步骤类型",
                    ),
                ),
                ("order", models.IntegerField(verbose_name="步骤顺序")),
                (
                    "approver_type",
                    models.CharField(
                        choices=[
                            ("specific_user", "指定用户"),
                            ("role_based", "基于角色"),
                            ("project_owner", "项目负责人"),
                            ("task_assignee", "任务负责人"),
                            ("any_member", "任意成员"),
                        ],
                        default="specific_user",
                        max_length=20,
                        verbose_name="审批人类型",
                    ),
                ),
                ("config", models.JSONField(default=dict, verbose_name="步骤配置")),
                (
                    "is_required",
                    models.BooleanField(default=True, verbose_name="是否必需"),
                ),
                (
                    "timeout_hours",
                    models.IntegerField(default=72, verbose_name="超时时间(小时)"),
                ),
                (
                    "approvers",
                    models.ManyToManyField(
                        blank=True,
                        related_name="workflow_steps",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="审批人",
                    ),
                ),
            ],
            options={
                "verbose_name": "工作流步骤",
                "verbose_name_plural": "工作流步骤",
                "ordering": ["workflow", "order"],
            },
        ),
        migrations.AddField(
            model_name="workflowinstance",
            name="current_step",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="workflows.workflowstep",
                verbose_name="当前步骤",
            ),
        ),
        migrations.CreateModel(
            name="WorkflowStepInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "等待中"),
                            ("in_progress", "进行中"),
                            ("completed", "已完成"),
                            ("skipped", "已跳过"),
                            ("error", "错误"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="开始时间"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="完成时间"
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("approved", "已批准"),
                            ("rejected", "已拒绝"),
                            ("skipped", "已跳过"),
                            ("error", "错误"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="步骤结果",
                    ),
                ),
                ("comments", models.TextField(blank=True, verbose_name="审批意见")),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="分配给",
                    ),
                ),
                (
                    "step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="workflows.workflowstep",
                        verbose_name="工作流步骤",
                    ),
                ),
                (
                    "workflow_instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="step_instances",
                        to="workflows.workflowinstance",
                        verbose_name="工作流实例",
                    ),
                ),
            ],
            options={
                "verbose_name": "工作流步骤实例",
                "verbose_name_plural": "工作流步骤实例",
                "ordering": ["workflow_instance", "step__order"],
            },
        ),
        migrations.CreateModel(
            name="WorkflowTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="工作流名称")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="工作流描述"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("task_approval", "任务审批"),
                            ("project_approval", "项目审批"),
                            ("change_request", "变更请求"),
                            ("issue_management", "问题管理"),
                            ("release_management", "发布管理"),
                            ("custom", "自定义"),
                        ],
                        default="custom",
                        max_length=50,
                        verbose_name="工作流类别",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "is_public",
                    models.BooleanField(default=False, verbose_name="是否公开"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
            ],
            options={
                "verbose_name": "工作流模板",
                "verbose_name_plural": "工作流模板",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="workflowstep",
            name="workflow",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="steps",
                to="workflows.workflowtemplate",
                verbose_name="工作流",
            ),
        ),
        migrations.AddField(
            model_name="workflowinstance",
            name="workflow",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="instances",
                to="workflows.workflowtemplate",
                verbose_name="工作流模板",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="workflowstep",
            unique_together={("workflow", "order")},
        ),
    ]
