# Generated by Django 5.2.1 on 2025-09-03 07:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "projects",
            "0002_project_actual_cost_project_budget_project_end_date_and_more",
        ),
        ("tasks", "0002_tasktag_task_actual_hours_task_completed_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Meeting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="会议标题")),
                ("description", models.TextField(verbose_name="会议描述")),
                (
                    "meeting_type",
                    models.CharField(
                        choices=[
                            ("project_review", "项目评审"),
                            ("team_sync", "团队同步"),
                            ("stakeholder", "干系人会议"),
                            ("planning", "规划会议"),
                            ("retrospective", "回顾会议"),
                            ("other", "其他"),
                        ],
                        max_length=30,
                        verbose_name="会议类型",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "已安排"),
                            ("in_progress", "进行中"),
                            ("completed", "已完成"),
                            ("cancelled", "已取消"),
                            ("postponed", "已延期"),
                        ],
                        default="scheduled",
                        max_length=20,
                        verbose_name="会议状态",
                    ),
                ),
                ("start_time", models.DateTimeField(verbose_name="开始时间")),
                ("end_time", models.DateTimeField(verbose_name="结束时间")),
                (
                    "timezone",
                    models.CharField(
                        default="Asia/Shanghai", max_length=50, verbose_name="时区"
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="会议地点"
                    ),
                ),
                ("meeting_url", models.URLField(blank=True, verbose_name="会议链接")),
                (
                    "meeting_id",
                    models.CharField(blank=True, max_length=100, verbose_name="会议ID"),
                ),
                (
                    "meeting_password",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="会议密码"
                    ),
                ),
                ("agenda", models.TextField(blank=True, verbose_name="会议议程")),
                (
                    "meeting_notes",
                    models.TextField(blank=True, verbose_name="会议记录"),
                ),
                ("action_items", models.JSONField(default=list, verbose_name="行动项")),
                (
                    "reminder_minutes",
                    models.IntegerField(default=15, verbose_name="提前提醒(分钟)"),
                ),
                (
                    "send_reminder",
                    models.BooleanField(default=True, verbose_name="发送提醒"),
                ),
                (
                    "attachments",
                    models.JSONField(default=list, verbose_name="会议附件"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "attendees",
                    models.ManyToManyField(
                        blank=True,
                        related_name="attending_meetings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="参与者",
                    ),
                ),
                (
                    "organizer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organized_meetings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="组织者",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meetings",
                        to="projects.project",
                        verbose_name="关联项目",
                    ),
                ),
                (
                    "required_attendees",
                    models.ManyToManyField(
                        blank=True,
                        related_name="required_meetings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="必需参与者",
                    ),
                ),
            ],
            options={
                "verbose_name": "会议",
                "verbose_name_plural": "会议",
                "ordering": ["start_time"],
            },
        ),
        migrations.CreateModel(
            name="TeamCalendar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="日历名称")),
                ("description", models.TextField(blank=True, verbose_name="日历描述")),
                (
                    "color",
                    models.CharField(
                        default="#007bff", max_length=7, verbose_name="日历颜色"
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(default=False, verbose_name="是否公开"),
                ),
                (
                    "default_reminder_minutes",
                    models.IntegerField(default=15, verbose_name="默认提醒时间(分钟)"),
                ),
                (
                    "working_hours_start",
                    models.TimeField(default="09:00", verbose_name="工作时间开始"),
                ),
                (
                    "working_hours_end",
                    models.TimeField(default="18:00", verbose_name="工作时间结束"),
                ),
                ("working_days", models.JSONField(default=list, verbose_name="工作日")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "can_edit",
                    models.ManyToManyField(
                        blank=True,
                        related_name="editable_calendars",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="可编辑用户",
                    ),
                ),
                (
                    "can_view",
                    models.ManyToManyField(
                        blank=True,
                        related_name="viewable_calendars",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="可查看用户",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_calendars",
                        to="projects.project",
                        verbose_name="关联项目",
                    ),
                ),
            ],
            options={
                "verbose_name": "团队日历",
                "verbose_name_plural": "团队日历",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CalendarEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="事件标题")),
                ("description", models.TextField(blank=True, verbose_name="事件描述")),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("meeting", "会议"),
                            ("deadline", "截止日期"),
                            ("milestone", "里程碑"),
                            ("reminder", "提醒"),
                            ("holiday", "假期"),
                            ("custom", "自定义"),
                        ],
                        max_length=20,
                        verbose_name="事件类型",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "低"),
                            ("normal", "普通"),
                            ("high", "高"),
                            ("urgent", "紧急"),
                        ],
                        default="normal",
                        max_length=10,
                        verbose_name="优先级",
                    ),
                ),
                ("start_time", models.DateTimeField(verbose_name="开始时间")),
                ("end_time", models.DateTimeField(verbose_name="结束时间")),
                (
                    "all_day",
                    models.BooleanField(default=False, verbose_name="全天事件"),
                ),
                (
                    "is_recurring",
                    models.BooleanField(default=False, verbose_name="是否重复"),
                ),
                (
                    "recurrence_rule",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="重复规则"
                    ),
                ),
                (
                    "recurrence_end",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="重复结束时间"
                    ),
                ),
                (
                    "location",
                    models.CharField(blank=True, max_length=200, verbose_name="地点"),
                ),
                (
                    "reminder_minutes",
                    models.IntegerField(default=15, verbose_name="提前提醒(分钟)"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否激活"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "attendees",
                    models.ManyToManyField(
                        blank=True,
                        related_name="attending_events",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="参与者",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_events",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calendar_events",
                        to="projects.project",
                        verbose_name="关联项目",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calendar_events",
                        to="tasks.task",
                        verbose_name="关联任务",
                    ),
                ),
            ],
            options={
                "verbose_name": "日历事件",
                "verbose_name_plural": "日历事件",
                "ordering": ["start_time"],
                "indexes": [
                    models.Index(
                        fields=["start_time", "end_time"],
                        name="calendar_ca_start_t_ec8af5_idx",
                    ),
                    models.Index(
                        fields=["creator", "start_time"],
                        name="calendar_ca_creator_709354_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="MeetingAttendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("invited", "已邀请"),
                            ("accepted", "已接受"),
                            ("declined", "已拒绝"),
                            ("tentative", "待定"),
                            ("attended", "已参加"),
                            ("absent", "缺席"),
                        ],
                        default="invited",
                        max_length=20,
                        verbose_name="出勤状态",
                    ),
                ),
                (
                    "response_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="响应时间"
                    ),
                ),
                (
                    "response_note",
                    models.TextField(blank=True, verbose_name="响应备注"),
                ),
                (
                    "joined_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="加入时间"
                    ),
                ),
                (
                    "left_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="离开时间"
                    ),
                ),
                (
                    "email_notification",
                    models.BooleanField(default=True, verbose_name="邮件通知"),
                ),
                (
                    "sms_notification",
                    models.BooleanField(default=False, verbose_name="短信通知"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "meeting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_records",
                        to="calendar.meeting",
                        verbose_name="会议",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meeting_attendance",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "会议出勤",
                "verbose_name_plural": "会议出勤",
                "ordering": ["meeting", "user"],
                "unique_together": {("meeting", "user")},
            },
        ),
    ]
