# Generated by Django 5.2.1 on 2025-09-03 07:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "projects",
            "0002_project_actual_cost_project_budget_project_end_date_and_more",
        ),
        ("tasks", "0002_tasktag_task_actual_hours_task_completed_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FileCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="分类名称")),
                ("description", models.TextField(blank=True, verbose_name="分类描述")),
                (
                    "color",
                    models.CharField(
                        default="#6c757d", max_length=7, verbose_name="分类颜色"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "文件分类",
                "verbose_name_plural": "文件分类",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ProjectFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="文件名")),
                (
                    "original_name",
                    models.CharField(max_length=255, verbose_name="原始文件名"),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="project_files/%Y/%m/%d/", verbose_name="文件"
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("document", "文档"),
                            ("image", "图片"),
                            ("video", "视频"),
                            ("audio", "音频"),
                            ("archive", "压缩包"),
                            ("code", "代码"),
                            ("other", "其他"),
                        ],
                        max_length=20,
                        verbose_name="文件类型",
                    ),
                ),
                ("file_size", models.BigIntegerField(verbose_name="文件大小(字节)")),
                (
                    "mime_type",
                    models.CharField(max_length=100, verbose_name="MIME类型"),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="上传时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("description", models.TextField(blank=True, verbose_name="文件描述")),
                (
                    "tags",
                    models.CharField(blank=True, max_length=500, verbose_name="标签"),
                ),
                (
                    "is_public",
                    models.BooleanField(default=False, verbose_name="是否公开"),
                ),
                (
                    "download_count",
                    models.IntegerField(default=0, verbose_name="下载次数"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="files.filecategory",
                        verbose_name="文件分类",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="projects.project",
                        verbose_name="所属项目",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="tasks.task",
                        verbose_name="关联任务",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="上传者",
                    ),
                ),
            ],
            options={
                "verbose_name": "项目文件",
                "verbose_name_plural": "项目文件",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="FileComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="评论内容")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="评论者",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="files.filecomment",
                        verbose_name="父评论",
                    ),
                ),
                (
                    "file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="files.projectfile",
                        verbose_name="文件",
                    ),
                ),
            ],
            options={
                "verbose_name": "文件评论",
                "verbose_name_plural": "文件评论",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="FileVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version_number",
                    models.CharField(max_length=20, verbose_name="版本号"),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="file_versions/%Y/%m/%d/", verbose_name="版本文件"
                    ),
                ),
                ("file_size", models.BigIntegerField(verbose_name="文件大小(字节)")),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="上传时间"),
                ),
                ("change_log", models.TextField(blank=True, verbose_name="变更说明")),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="上传者",
                    ),
                ),
            ],
            options={
                "verbose_name": "文件版本",
                "verbose_name_plural": "文件版本",
                "ordering": ["-uploaded_at"],
                "unique_together": {("file", "version_number")},
            },
        ),
    ]
