# Generated by Django 5.2.1 on 2025-09-03 07:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="模板名称")),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("task_assigned", "任务分配"),
                            ("task_completed", "任务完成"),
                            ("task_overdue", "任务逾期"),
                            ("comment_added", "新增评论"),
                            ("file_uploaded", "文件上传"),
                            ("project_update", "项目更新"),
                            ("milestone_reached", "里程碑达成"),
                            ("deadline_approaching", "截止日期临近"),
                            ("team_invitation", "团队邀请"),
                            ("system_alert", "系统提醒"),
                        ],
                        max_length=30,
                        verbose_name="通知类型",
                    ),
                ),
                (
                    "title_template",
                    models.CharField(max_length=255, verbose_name="标题模板"),
                ),
                ("message_template", models.TextField(verbose_name="内容模板")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "通知模板",
                "verbose_name_plural": "通知模板",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="UserNotificationSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email_notifications",
                    models.BooleanField(default=True, verbose_name="启用邮件通知"),
                ),
                (
                    "email_frequency",
                    models.CharField(
                        choices=[
                            ("immediate", "立即"),
                            ("hourly", "每小时"),
                            ("daily", "每日"),
                            ("weekly", "每周"),
                        ],
                        default="immediate",
                        max_length=20,
                        verbose_name="邮件频率",
                    ),
                ),
                (
                    "site_notifications",
                    models.BooleanField(default=True, verbose_name="启用站内通知"),
                ),
                (
                    "browser_notifications",
                    models.BooleanField(default=True, verbose_name="启用浏览器通知"),
                ),
                (
                    "task_notifications",
                    models.BooleanField(default=True, verbose_name="任务相关通知"),
                ),
                (
                    "project_notifications",
                    models.BooleanField(default=True, verbose_name="项目相关通知"),
                ),
                (
                    "comment_notifications",
                    models.BooleanField(default=True, verbose_name="评论相关通知"),
                ),
                (
                    "file_notifications",
                    models.BooleanField(default=True, verbose_name="文件相关通知"),
                ),
                (
                    "quiet_hours_start",
                    models.TimeField(
                        blank=True, null=True, verbose_name="免打扰开始时间"
                    ),
                ),
                (
                    "quiet_hours_end",
                    models.TimeField(
                        blank=True, null=True, verbose_name="免打扰结束时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_settings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户通知设置",
                "verbose_name_plural": "用户通知设置",
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("task_assigned", "任务分配"),
                            ("task_completed", "任务完成"),
                            ("task_overdue", "任务逾期"),
                            ("comment_added", "新增评论"),
                            ("file_uploaded", "文件上传"),
                            ("project_update", "项目更新"),
                            ("milestone_reached", "里程碑达成"),
                            ("deadline_approaching", "截止日期临近"),
                            ("team_invitation", "团队邀请"),
                            ("system_alert", "系统提醒"),
                        ],
                        max_length=30,
                        verbose_name="通知类型",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="通知标题")),
                ("message", models.TextField(verbose_name="通知内容")),
                ("object_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "is_read",
                    models.BooleanField(default=False, verbose_name="是否已读"),
                ),
                (
                    "is_sent",
                    models.BooleanField(default=False, verbose_name="是否已发送"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="阅读时间"
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "低"),
                            ("normal", "普通"),
                            ("high", "高"),
                            ("urgent", "紧急"),
                        ],
                        default="normal",
                        max_length=10,
                        verbose_name="通知优先级",
                    ),
                ),
                ("channels", models.JSONField(default=list, verbose_name="通知渠道")),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="接收者",
                    ),
                ),
            ],
            options={
                "verbose_name": "通知",
                "verbose_name_plural": "通知",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient", "is_read"],
                        name="notificatio_recipie_4e3567_idx",
                    ),
                    models.Index(
                        fields=["notification_type", "created_at"],
                        name="notificatio_notific_f2e0f7_idx",
                    ),
                ],
            },
        ),
    ]
